/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/u4jvoHG2dVK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Switch } from "@/components/ui/switch"
import { Label } from "@/components/ui/label"

export function Calc() {
  return (
    <div className="p-4 bg-white rounded-lg shadow-md">
      <div className="grid grid-cols-1 gap-4 md:grid-cols-5">
        <Select>
          <SelectTrigger id="destination">
            <SelectValue placeholder="Куда поедете" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="destination1">Destination 1</SelectItem>
            <SelectItem value="destination2">Destination 2</SelectItem>
          </SelectContent>
        </Select>
        <div className="relative">
          <Input type="text" placeholder="Уезжаете" className="pl-10" />
          <CalendarIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
        </div>
        <div className="relative">
          <Input type="text" placeholder="Возвращаетесь" className="pl-10" />
          <CalendarIcon className="absolute left-2.5 top-2.5 h-4 w-4 text-muted-foreground" />
        </div>
        <Select>
          <SelectTrigger id="age">
            <SelectValue placeholder="Возраст тур..." />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="age1">Age 1</SelectItem>
            <SelectItem value="age2">Age 2</SelectItem>
          </SelectContent>
        </Select>
        <Button className="bg-[#00303f] text-white">Показать цены</Button>
      </div>
      <div className="flex items-center mt-4">
        <Switch id="traveling" />
        <Label htmlFor="traveling" className="ml-2">
          Уже путешествую
        </Label>
        <CircleHelpIcon className="ml-2 h-4 w-4 text-muted-foreground" />
      </div>
    </div>
  )
}

function CalendarIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function CircleHelpIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3" />
      <path d="M12 17h.01" />
    </svg>
  )
}
